image: image: rocker/tidyverse:latest

pages:
  stage: deploy

  script:
    - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
    - Rscript -e 'remotes::install_gitlab("dickoa/cgalheaders")'
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'

  artifacts:
    paths:
      - public
